### PR TITLE
Update to Ubuntu 20.04 + GCC 10 and add clang-11 and clang-12

### PR DESCRIPTION
**Pull request by WolleTD**
At first, I just wanted to add clang-11, but then I realized clang-12 is already in Release Candidate phase, so I added that as well.

clang-12, though, uses CMake's `find_package` which only found shared libraries for our static build. After some digging, I found a `LLVM_BUILD_STATIC` flag, available in all Versions, that makes clang-12 search for static libraries instead.
This also adds the `-static` flag to the compiler for us in all versions. By using `CMAKE_CXX_FLAGS` instead of `CMAKE_CXX_FLAGS_MINSIZEREL`, we don't override those flags and can make use of that.

During my research, GitHub removed gcc-8 from the runners (https://github.com/actions/virtual-environments/commit/54fa1d6658ac69773fdc2e79d82f6358cbfe37f7), so I moved all Linux builds to gcc-10 and also switched to Ubuntu 20.04 while on it.

clang-8 failed to compile with gcc-10 due to missing includes. which is fixed by patching https://github.com/llvm/llvm-project/commit/b288d90b39f4b905c02092a9bfcfd6d78f99b191 into it.

clang-8, -9 and -10 failed to link on Ubuntu 20.04 because libz3 _is_ available. The mechanism to alter `find_package` behaviour is only introduced in clang-12, so only the shared library is found. Since clang-11, the Z3 solver is disabled by default.
As everything worked fine without libz3 on Ubuntu 18.04, I simply disabled the Z3 solver on those three versions as well.
clang-8 uses a different flag here than clang-9 and clang-10.

All versions built tonight: https://github.com/WolleTD/clang-tools-static-binaries/releases/tag/test-973a464e

I'll keep this as a draft until clang 12 is finally released.

### CODE REVIEW

**Review by muttleyxd — APPROVED** [review]
Great changes, thanks for your PR! :grinning:

**Comment by muttleyxd** [comment]
> I'll keep this as a draft until clang 12 is finally released.

Sure, just ping me when it's ready and we will merge :+1:

**Comment by WolleTD** [comment]
Hey, I wanted to get to know GH Actions better and was able to merge everything into a single matrix job: https://github.com/WolleTD/clang-tools-static-binaries/commit/9b8196e4806ff1b649253b331e7485e70b5ba43f
As a neat side effect, this allows pushing all 180 artifacts into a single draft.
If you are interested, I'd update the PR accordingly.

**Comment by muttleyxd** [comment]
This is awesome, I'm definitely up for this :+1:

**Comment by WolleTD** [comment]
Had a stressful week at work, but now LLVM 12 is ready as well. I updated the branch accordingly. I reordered it to have clang 11 and 12 added after creating the matrix job.

I discovered that – on Linux and OSX, at least – clang 3.9 through 8 builds are reproducible. From version 9 onwards, the commit hash of this repository leaks into the binaries.
We now download a tarball of this repository instead of using `actions/checkout`. This avoids creating a .git-Repository and makes all Linux and MacOS builds reproducible.

Some of the steps now explicitly use `shell: bash` (Git Bash on Windows) to get rid of my `matrix.set-env` and `matrix.get-ver` hacks, making the code less obfuscated.

**Comment by muttleyxd** [comment]
Great job, especially with how you got all of this into one file. Thanks for your contribution!

**Pull request merged**
